Create a category for launching inbound agents from console
jenkinsci/remoting pull request #453
Opened 2021-05-13 18:48 UTC by oleg-nenashev

Needed for replacing https://wiki.jenkins.io/display/JENKINS/Launching+agent+from+console in the implementation

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2021-05-14 08:58 UTC, agentgonzo approved these changes

2021-05-17 02:17 UTC, jeffret-b requested changes
Requesting changes for the new mention of "JNLP files", which is incorrect.

Beyond that, I don't see the value in this proposal. This documentation could certainly be improved but I don't see how these changes provide improvement.

One area that could be improved, if we still want to support it, is the description on "Install as a Windows service", which references old, poorly done documentation from the wiki.

2021-05-17 02:17 UTC, jeffret-b commented on docs/inbound-agent.md
> +This is the only launch mechanism that actually uses Java Web Start and the JNLP files.
The last part is incorrect. The item below, "Download JNLP file", clearly uses the JNLP file, though it doesn't use JNLP (or Web Start).

2021-12-01 00:39 UTC, jeffret-b commented
This PR is apparently abandoned so I'm closing it.

2021-12-01 00:39 UTC, closed without merging