feat: custom connection headers
jenkinsci/remoting pull request #455
Opened 2021-05-18 14:59 UTC by agentgonzo

Add the -connectionHeaders flag to add additional custom headers to the connection request.

These additional headers are then used when connecting to jenkins either via JNLP or websockets. 

Use-case: You have a reverse proxy in front of jenkins that requires custom headers to authenticate/route correctly.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2021-05-18 15:01 UTC, agentgonzo commented
@jglick @oleg-nenashev @abayer - I could do with some additional guidance of how to test this, as I couldn't find any existing tests. 

our primary use-case is to support headers in websockets, but it made sense to add them to the JNLP connection as well.

2021-05-18 15:54 UTC, oleg-nenashev approved these changes

2021-05-18 16:15 UTC, jglick commented
> it made sense to add them to the JNLP connection as well

Does it? The only thing the HTTP connection for TCP inbound agents (please do not say _JNLP_ unless you really mean it) does is to get a host & port, which is public information (an unauthenticated endpoint) and generally static. The actual TCP connection uses a custom protocol, so you could not interpret any custom headers in a reverse proxy—if you could even use a reverse proxy with a TCP agent at all.

I would limit the addition to WebSocket agents unless and until there is a use case for doing something with TCP agents, which might look very different.

2021-05-19 00:58 UTC, jeffret-b requested changes
As Jesse mentions, let's not add the headers to the TCP protocol, as they don't make any sense there. Unless there is an identified use case for that.

2021-05-19 09:42 UTC, agentgonzo commented
Thanks @jglick @jeffret-b . Can you take a look at #458 please?

2021-05-19 09:42 UTC, closed without merging